package sqlconstants

const DB_TYPE_SQLITE3 = "sqlite3"
const SQLITE3_FILE_URL = "throttle.db"
const SQLITE3_CONNECTION_STRING = "file:" + SQLITE3_FILE_URL

const CHECK_IF_TABLE_EXISTS_SQLITE3 = "SELECT NAME FROM SQLITE WHERE TYPE=? AND NAME=?;"
const CREATE_BUCKET_SCHEMA = "CREATE TABLE BUCKETS(NAME TEXT NOT NULL UNIQUE PRIMARY KEY, VOLUME INTEGER, CAPACITY INTEGER, TIMEFRAME INTEGER, CREATED_TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UPDATED_TIMESTAMP TEXT)"
